### ISSUE TITLE
Some Errors in 3.2 Alfa Latest Build

### ISSUE THREAD

**Issue by hxika** [dairin0d/blender-2.8-scripts#12]
Traceback (most recent call last):
  File "D:\Portable\blender-3\3.2\scripts\modules\addon_utils.py", line 371, in enable
    mod.register()
  File "C:\Users\Roman\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mouselook_navigation\__init__.py", line 2400, in register
    addon.register()
  File "C:\Users\Roman\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mouselook_navigation\dairin0d\utils_addon.py", line 746, in register
    self.__register_class(self.classes_new.popitem(last=False)[0])
  File "C:\Users\Roman\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mouselook_navigation\dairin0d\utils_addon.py", line 724, in __register_class
    self.__register_class_annotations(cls, prop_infos)
  File "C:\Users\Roman\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mouselook_navigation\dairin0d\utils_addon.py", line 712, in __register_class_annotations
    bpy.utils.register_class(cls)
ValueError: bpy_struct "mouselook_navigation-preferences" registration error: 'raycast_modes' EnumProperty could not register (see previous error)

**Comment by dairin0d** [comment]
Thanks, sorry for the delay.
Try the latest version, this should be fixed now.

**Comment by hxika** [comment]
Thank You!
