### ISSUE TITLE
raycast_modes EnumProperty could not register

### ISSUE THREAD

**Issue by dairin0d** [dairin0d/blender-2.8-scripts#19]
Reported by @joebreaker:

Hey! 
Thanks for this wonderful addon!
I've been reckless enough not to remove the old version of the MouseLook Navigation. 
Now I cannot install neither of the versions(((

Could you please help me out?

it reads this:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Professional\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mouselook_navigation\__init__.py", line 2400, in register
    addon.register()
  File "C:\Users\Professional\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mouselook_navigation\dairin0d\utils_addon.py", line 746, in register
    self.__register_class(self.classes_new.popitem(last=False)[0])
  File "C:\Users\Professional\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mouselook_navigation\dairin0d\utils_addon.py", line 724, in __register_class
    self.__register_class_annotations(cls, prop_infos)
  File "C:\Users\Professional\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mouselook_navigation\dairin0d\utils_addon.py", line 712, in __register_class_annotations
    bpy.utils.register_class(cls)
ValueError: bpy_struct "mouselook_navigation-preferences" registration error: 'raycast_modes' EnumProperty could not register (see previous error)

_Originally posted by @joebreaker in https://github.com/dairin0d/blender-2.8-scripts/issues/11#issuecomment-1483799869_

**Comment by dairin0d** [comment]
The last line says "see previous error". Are there any other errors in the console?

How did you install the addon? Can you remove all installed versions of MouseLook Navigation that you have, and install it from scratch?
